version: "2"

# plugins:
#   eslint:
#     enabled: true
#     channel: "eslint-4"
#     config:
#       config: .eslintrc.json

checks:
  method-complexity:
    enabled: false
  similar-code:
    enabled: false
  identical-code:
    enabled: false

ratings:
   paths:
    - "**.js"
    - "**.jsx"
    - "**.css"

exclude_paths:
- static/**/*